### ISSUE TITLE
Broken on Mac OSX

### ISSUE THREAD

**Issue by Sija** [crystal-lang-tools/atom-ide-crystal#1]
See https://github.com/steelbrain/atom-linter/issues/143

**Comment by keplersj** [comment]
What version of Atom are you running? I code on a Mac, using Crystal installed from Homebrew, so I'm trying to find the discrepancy in our environments.

**Comment by Sija** [comment]
latest, which is `1.9.7` for the time being.

**Comment by keplersj** [comment]
Does linting work if you set the "Compiler Executable Path" config to `/usr/local/bin/crystal`?

**Comment by Sija** [comment]
nope, no difference.
