### ISSUE TITLE
Can't find crystal even though I specified a path

### ISSUE THREAD

**Issue by timuckun** [crystal-lang-tools/atom-ide-crystal#11]
I am getting an error it can't find crystal even though I set /usr/local/bin/crystal as the command. Using MacOSX just upgraded atom to 1.12

**Comment by timuckun** [comment]
This is the error

'crystal' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

it is in my path and I specified the exact path in the settings.

**Comment by watzon** [comment]
Also getting this, I'm using a workaround on WSL, but crystal is definitely on my path and I can execute it through command prompt

**Comment by keplersj** [comment]
This package will move to a Language Server Protocol implementation using [scry](https://github.com/kofno/scry) when kofno/scry#15 is merged. Moving to the scry backend will resolve this issue.

**Comment by keplersj** [comment]
Moved to a [`scry`](https://github.com/crystal-lang-tools/scry) based implementation. No longer relevant.
