### ISSUE TITLE
I think format on save is crashing atom 

### ISSUE THREAD

**Issue by timuckun** [crystal-lang-tools/atom-ide-crystal#13]
It doesn't happen all the time but it only crashes when I save. It crashes a lot but not 100% of the time. 

Is this project still alive?

**Comment by keplersj** [comment]
This package will move to a Language Server Protocol implementation using [scry](https://github.com/kofno/scry) when kofno/scry#15 is merged. Moving to the scry backend will resolve this issue.

**Comment by keplersj** [comment]
Moved to a [`scry`](https://github.com/crystal-lang-tools/scry) based implementation. No longer relevant.
