### ISSUE TITLE
It does not recognize the file as a crystal one, it says ruby

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang-tools/atom-ide-crystal#15]
![screen shot 2017-05-07 at 12 57 11 am](https://cloud.githubusercontent.com/assets/764271/25778327/23565a14-32c0-11e7-804e-174819469ee1.png)

**Comment by keplersj** [comment]
Not technically an issue with this package... Mind opening an issue with [atom-crystal/language-crystal](https://github.com/atom-crystal/language-crystal)?
