### ISSUE TITLE
0.2.1 Freezes

### ISSUE THREAD

**Issue by jwaldrip** [crystal-lang-tools/atom-ide-crystal#16]
It seems as though 0.2.1 freezes on save. I have rolled back to 0.2.0 and everything works fine.

**Comment by keplersj** [comment]
This package will move to a Language Server Protocol implementation using [scry](https://github.com/kofno/scry) when kofno/scry#15 is merged. Moving to the scry backend will resolve this issue.

**Comment by keplersj** [comment]
Closed according to #18. Please reopen if #18 does not resolve the issue.
