### ISSUE TITLE
It hangs when running diagnostics on file

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang-tools/atom-ide-crystal#17]
![screen shot 2017-05-22 at 1 14 48 pm](https://cloud.githubusercontent.com/assets/764271/26322434/ae7f17b6-3ef0-11e7-91f5-da37ddf71424.png)

**Comment by keplersj** [comment]
This package will move to a Language Server Protocol implementation using [scry](https://github.com/kofno/scry) when kofno/scry#15 is merged. Moving to the scry backend will resolve this issue.

**Comment by keplersj** [comment]
Closed according to #18. Please reopen if #18 does not resolve the issue.
