### ISSUE TITLE
atom-crystal icon is broken

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang-tools/atom-ide-crystal#21]
Atom.io doesn't show `atom-crystal` icon.

![capture2](https://user-images.githubusercontent.com/3067335/29199847-48fc0eea-7e1e-11e7-8596-bb67db8d1b96.PNG)

Maybe, it need to be updated to `crystal-lang-tools` too?

**Comment by keplersj** [comment]
The transition isn't finished.
