### ISSUE TITLE
Crystal tool format doesn't work when enabled

### ISSUE THREAD

**Issue by mrkaspa** [crystal-lang-tools/atom-ide-crystal#8]

**Comment by keplersj** [comment]
Can I get a reproducible environment to verify? Maybe just some code snippets of code you expect to format?

**Comment by mrkaspa** [comment]
I just expected to format this:

``` crystal
module Demo
class Cool
end
end
```

**Comment by mrkaspa** [comment]
These are my settings

![screen shot 2016-10-16 at 2 56 27 pm](https://cloud.githubusercontent.com/assets/764271/19420435/c26fd1ca-93b0-11e6-8426-5f3dcfc6e7fe.png)

**Comment by mrkaspa** [comment]
@keplersj btw I'm using OSX

**Comment by keplersj** [comment]
This package will move to a Language Server Protocol implementation using [scry](https://github.com/kofno/scry) when kofno/scry#15 is merged. Moving to the scry backend will resolve this issue.

**Comment by keplersj** [comment]
Moved to a [`scry`](https://github.com/crystal-lang-tools/scry) based implementation. No longer relevant.
